var arr = [1, 24, 6, "haha", null, false];
console.log(arr.length);
arr[1] = 99;
console.log(arr[1]);
var arrcopy = arr.slice();
console.log(arrcopy);
console.log(arrcopy.slice(2, 5));
arrcopy.push("zxc", 123);
console.log(arrcopy);
arrcopy.pop();
console.log(arrcopy);
arrcopy.unshift('a', 100);
console.log(arrcopy);
arrcopy.shift();
console.log(arrcopy);
arrcopy.sort();
console.log(arrcopy);
arrcopy.reverse();
console.log(arrcopy);
arrcopy.splice(2, 2, "splice1", "splice2");
console.log(arrcopy);
arrcopy.splice(3,2);
console.log(arrcopy);
arrcopy.splice(4, 0, 'google', 'bing');
console.log(arrcopy);
arrcopy.splice(3, 4);
arrcopy = arrcopy.concat(['concat1','concat2']);
console.log(arrcopy);
console.log(arrcopy.join('='));
var comboarr = [arr, arrcopy];
console.log(comboarr[1][4]);